"""Add LoadBalancer and ServiceInstance

Revision ID: 089f9bd2f8bd
Revises: cd261ed60b84
Create Date: 2026-08-07 08:53:43.854226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089f9bd2f8bd'
down_revision = 'cd261ed60b84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    # Create the new enum type for load_balancer_strategy
    load_balancer_strategy_enum = postgresql.ENUM('ROUND_ROBIN', 'LEAST_CONNECTIONS', 'WEIGHTED_ROUND_ROBIN', 'RANDOM', 'HEALTH_AWARE', name='loadbalancerstrategy')
    load_balancer_strategy_enum.create(op.get_bind())

    op.create_table('service_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('HEALTHY', 'UNHEALTHY', 'UNKNOWN', 'IMPORTING', name='servicestatus', create_type=False), nullable=False),
    sa.Column('active_connections', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_instances_id'), 'service_instances', ['id'], unique=False)
    op.create_index(op.f('ix_service_instances_instance_id'), 'service_instances', ['instance_id'], unique=True)
    op.add_column('services', sa.Column('load_balancer_strategy', postgresql.ENUM('ROUND_ROBIN', 'LEAST_CONNECTIONS', 'WEIGHTED_ROUND_ROBIN', 'RANDOM', 'HEALTH_AWARE', name='loadbalancerstrategy', create_type=False), nullable=False, server_default='ROUND_ROBIN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'load_balancer_strategy')
    op.drop_index(op.f('ix_service_instances_instance_id'), table_name='service_instances')
    op.drop_index(op.f('ix_service_instances_id'), table_name='service_instances')
    op.drop_table('service_instances')
    # ### end Alembic commands ###
