"""Add RateLimitPolicy

Revision ID: a58f28beed21
Revises: 2462e1a85c97
Create Date: 2026-08-05 19:05:49.291228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58f28beed21'
down_revision = '2462e1a85c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_path', sa.String(length=255), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('SLIDING_WINDOW_LOG', 'SLIDING_WINDOW_COUNTER', 'TOKEN_BUCKET', 'FIXED_WINDOW', 'ADAPTIVE', name='ratelimitalgorithm'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_policies_id'), 'rate_limit_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_policies_id'), table_name='rate_limit_policies')
    op.drop_table('rate_limit_policies')
    # ### end Alembic commands ###
