"""Add ResiliencePolicy

Revision ID: cd261ed60b84
Revises: a58f28beed21
Create Date: 2026-08-05 19:58:08.106164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd261ed60b84'
down_revision = 'a58f28beed21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resilience_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_timeout', sa.Integer(), nullable=False),
    sa.Column('half_open_requests', sa.Integer(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('request_timeout', sa.Integer(), nullable=False),
    sa.Column('fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_index(op.f('ix_resilience_policies_id'), 'resilience_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resilience_policies_id'), table_name='resilience_policies')
    op.drop_table('resilience_policies')
    # ### end Alembic commands ###
